apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: gcr.io/mindmend-production/mindmend:latest
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: mindmend-secrets
        - configMapRef:
            name: mindmend-config
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
