apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: admin@mindmend.xyz
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: gce
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mindmend-cert
  namespace: mindmend
spec:
  secretName: mindmend-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
    - mindmend.xyz

