apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mindmend-gsm
  namespace: mindmend
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/mindmend-production/secrets/database-url/versions/latest"
        path: "DATABASE_URL"
      - resourceName: "projects/mindmend-production/secrets/redis-url/versions/latest"
        path: "REDIS_URL"
      - resourceName: "projects/mindmend-production/secrets/openai-api-key/versions/latest"
        path: "OPENAI_API_KEY"
      - resourceName: "projects/mindmend-production/secrets/stripe-secret-key/versions/latest"
        path: "STRIPE_SECRET_KEY"
      - resourceName: "projects/mindmend-production/secrets/stripe-publishable-key/versions/latest"
        path: "STRIPE_PUBLISHABLE_KEY"
      - resourceName: "projects/mindmend-production/secrets/session-secret/versions/latest"
        path: "SESSION_SECRET"
      - resourceName: "projects/mindmend-production/secrets/email-host/versions/latest"
        path: "EMAIL_HOST"
      - resourceName: "projects/mindmend-production/secrets/email-port/versions/latest"
        path: "EMAIL_PORT"
      - resourceName: "projects/mindmend-production/secrets/email-user/versions/latest"
        path: "EMAIL_USER"
      - resourceName: "projects/mindmend-production/secrets/email-password/versions/latest"
        path: "EMAIL_PASSWORD"
      - resourceName: "projects/mindmend-production/secrets/email-from/versions/latest"
        path: "EMAIL_FROM"
  secretObjects:
    - secretName: mindmend-secrets-gsm
      type: Opaque
      data:
        - objectName: DATABASE_URL
          key: DATABASE_URL
        - objectName: REDIS_URL
          key: REDIS_URL
        - objectName: OPENAI_API_KEY
          key: OPENAI_API_KEY
        - objectName: STRIPE_SECRET_KEY
          key: STRIPE_SECRET_KEY
        - objectName: STRIPE_PUBLISHABLE_KEY
          key: STRIPE_PUBLISHABLE_KEY
        - objectName: SESSION_SECRET
          key: SESSION_SECRET
        - objectName: EMAIL_HOST
          key: EMAIL_HOST
        - objectName: EMAIL_PORT
          key: EMAIL_PORT
        - objectName: EMAIL_USER
          key: EMAIL_USER
        - objectName: EMAIL_PASSWORD
          key: EMAIL_PASSWORD
        - objectName: EMAIL_FROM
          key: EMAIL_FROM
