apiVersion: v1
kind: Secret
metadata:
  name: mindmend-secrets
  namespace: mindmend
type: Opaque
stringData:
  DATABASE_URL: postgresql://mindmend_user:CHANGE_ME@postgres:5432/mindmend_production
  REDIS_URL: redis://redis:6379/0
  OPENAI_API_KEY: CHANGE_ME
  STRIPE_SECRET_KEY: CHANGE_ME
  STRIPE_PUBLISHABLE_KEY: CHANGE_ME
  SESSION_SECRET: CHANGE_ME
  POSTGRES_USER: mindmend_user
  POSTGRES_PASSWORD: CHANGE_ME

