apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mindmend-gsm
  namespace: mindmend
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/mindmend-production/secrets/admin-email/versions/latest"
        path: "ADMIN_EMAIL"
      - resourceName: "projects/mindmend-production/secrets/admin-password/versions/latest"
        path: "ADMIN_PASSWORD"
  secretObjects:
    - secretName: mindmend-secrets-gsm
      type: Opaque
      data:
        - objectName: ADMIN_EMAIL
          key: ADMIN_EMAIL
        - objectName: ADMIN_PASSWORD
          key: ADMIN_PASSWORD

